<a href="https://colab.research.google.com/github/vedant16052006/Data_Science_lab/blob/main/MatrixOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3x3 Determinante

In [1]:
import numpy as np

# Define a 3x3 matrix
matrix_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 Matrix:")
display(matrix_3x3)

Original 3x3 Matrix:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
# Compute the determinant of the 3x3 matrix
determinant = np.linalg.det(matrix_3x3)

print(f"Determinant of the matrix: {determinant}")

Determinant of the matrix: 0.0


# Inverse Matrix

In [3]:
import numpy as np

# Define a new invertible 3x3 matrix
matrix_invertible = np.array([
    [1, 2, 0],
    [0, 1, 0],
    [0, 0, 1]
])

print("New Invertible 3x3 Matrix:")
display(matrix_invertible)

New Invertible 3x3 Matrix:


array([[1, 2, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
# Compute the determinant of the new matrix
determinant_invertible = np.linalg.det(matrix_invertible)

print(f"Determinant of the new matrix: {determinant_invertible}")

# Compute the inverse of the new matrix if determinant is non-zero
if determinant_invertible != 0:
    inverse_matrix = np.linalg.inv(matrix_invertible)
    print("\nInverse of the new matrix:")
    display(inverse_matrix)
else:
    print("\nThe new matrix is singular and does not have an inverse.")

Determinant of the new matrix: 1.0

Inverse of the new matrix:


array([[ 1., -2.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# Linear

In [5]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constant vector B
B = np.array([10, 20])

print("Coefficient Matrix A:")
display(A)
print("Constant Vector B:")
display(B)

Coefficient Matrix A:


array([[2, 3],
       [4, 5]])

Constant Vector B:


array([10, 20])

In [6]:
# Solve the system of linear equations Ax = B for x
# np.linalg.solve is preferred over direct inverse multiplication for numerical stability
solution = np.linalg.solve(A, B)

print(f"The solution for x and y is: {solution}")
print(f"So, x = {solution[0]:.2f} and y = {solution[1]:.2f}")

The solution for x and y is: [5. 0.]
So, x = 5.00 and y = 0.00
